@baseUrl = http://localhost:3333


GET  {{baseUrl}}/barbershops

###

GET {{baseUrl}}/barbershops/0deb0342-3ff2-4b79-a554-cc36f85450a4

###
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "code": "4/0AcvDMrAu9o4tKOlldN6fbqY_QftNZWwoyWgAxkTXPfMvqv_jxAK7GKNB7-QqvfSAYLfpvg"
}